# Generated by Django 3.2.16 on 2023-02-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('A', 'In Cart'), ('N', 'Not in Cart')], default='N', max_length=1),
        ),
    ]
